### ISSUE TITLE
overlapping of the elements

### ISSUE THREAD

**Issue by Arraxx** [fluid-project/infusion-docs#154] opened 2020-02-27 16:44 UTC
## Bug Description:
while resizing the page the navbar elements are just getting out and "+show reference" is overlapping the logo of infusion
## screenshot:
![Screenshot from 2020-02-27 21-59-57](https://user-images.githubusercontent.com/54955755/75465306-775d3480-59ae-11ea-8ca5-b9ae5edd1bf1.png)

## additional text:
i would like to take this issue.

**Comment by coderbabu10** [comment] 2020-02-27 16:44
@jhung @jobara what are your views?

**Comment by coderbabu10** [comment] 2020-02-28 07:29
i think we can add a toggle button will be good in the navbar as the contents in it will get hidden and we can decrease the size of  "show preference" by making its height and width little small that it doesn't collides with the elements in the navbar.

**Comment by coderbabu10** [comment] 2020-02-28 16:37
we can add the toggle button by using bootstrap 4.
@jhung @jobara

**Comment by jobara** [comment] 2020-03-02 18:31
@coderbabu10 this site is currently using Foundation. That's not to say we have to stick with foundation but it's unlikely we'll want to be using two CSS frameworks.

**Comment by coderbabu10** [comment] 2020-03-03 10:58
so what should i do now,should i implement it using the simple css,please guide me?
@jobara 
and sorry to ask you here but o am not able to find out infusion chat room can you send me the link for the same.
thank you

**Comment by jobara** [comment] 2020-03-03 12:13
@coderbabu10 information about the fluid-work IRC channel and IRC mailing list can be found on the [Get Involved](https://wiki.fluidproject.org/display/fluid/Get+Involved
) page of the wiki.

@jhung do you have thoughts about this.

**Comment by jobara** [comment] 2021-05-04 19:12
Duplicate of #158

**Closed by jobara** 2021-05-04 19:12 UTC
Labels: duplicate
