### ISSUE TITLE
nothing properly alligned in the mobile view

### ISSUE THREAD

**Issue by Arraxx** [fluid-project/infusion-docs#158] opened 2020-02-29 18:49 UTC
## screenshot:
![Screenshot from 2020-02-29 23-47-52](https://user-images.githubusercontent.com/54955755/75613333-55041c00-5b52-11ea-8cae-e2bbf6e8cc7e.png)

**Comment by coderbabu10** [comment] 2020-02-29 18:52
we can do changes like we can remove the whole left part and can put it inside a small button .
what do you think? @jobara

**Comment by jobara** [comment] 2020-03-02 18:34
@coderbabu10 I'm not sure which parts are not aligned. Could you provide more details on the issue. Make sure that you are describing things clearly enough that if someone is unable to see the screenshot, they still have an idea of what the issue is.

**Comment by coderbabu10** [comment] 2020-03-02 19:01
while making the site in the mobile view :
1.the element of the navbar are getting out.
2.'show preference' is overlapping with the logo.
3.the elements under the search bar is shown not the main elements of the infusion docs page.
4.the navbar is not properly shown it is also getting overlapped by the components under the searchbar.

**Comment by coderbabu10** [comment] 2020-03-02 19:02
i think i can work on this issue can you please assign me with the same?
@jobara @jhung

**Comment by coderbabu10** [comment] 2020-03-05 21:17
@jobara sir i have checked all the pages all having the same error none of the page is looking in a good position in mobile view please have a look.

**Comment by jobara** [comment] 2020-03-05 21:48
@coderbabu10 thank you for the issue and the description of the problem. I think this site will need some design thinking into how it should look and behave on smaller screens.

**Comment by coderbabu10** [comment] 2020-03-07 06:00
okay can i suggest for some design changes?
@jobara

**Comment by jobara** [comment] 2020-03-09 11:52
@coderbabu10 it will likely need to go through our design process with our design team.

**Comment by greatislander** [comment] 2021-05-05 20:54
I'm going to close this as we will likely be exploring a more comprehensive set of design improvements.

**Closed by greatislander** 2021-05-05 20:54 UTC
Labels: bug, question
